import sqlalchemy

type_dict = {
    'agency': [('agency_url', 'text'), ('agency_name', 'text'),
               ('agency_timezone', 'text'), ('agency_id', 'text'),
               ('agency_lang', 'text')],
    'calendar_dates': [('date', 'integer'), ('service_id', 'text'),
                ('exception_type', 'integer')],
    'fare_attributes': [('payment_method', 'integer'), ('price', 'real'),
                       ('currency_type', 'text'), ('fare_id', 'text'),
                       ('transfer_duration', 'integer'), ('transfers', 'text')],
    'fare_rules': [('route_id', 'integer'), ('fare_id', 'text'),
                 ('contains_id', 'text'), ('destination_id', 'text'),
                 ('origin_id', 'text')],
    'frequencies': [('headway_secs', 'integer'), ('start_time', 'interval'),
                  ('trip_id', 'text'), ('end_time', 'text')],
    'routes': [('route_long_name', 'text'), ('route_type', 'integer'),
            ('route_text_color', 'text'), ('route_color', 'text'),
            ('agency_id', 'text'), ('route_id', 'integer'),
            ('route_url', 'text'), ('route_short_name', 'integer')],
    'shapes': [('shape_pt_lat', 'real'), ('shape_id', 'text'),
            ('shape_pt_lon', 'real'), ('shape_pt_sequence', 'text')],
    'stop_times': [('arrival_time', 'interval'), ('trip_id', 'text'),
                ('stop_sequence', 'integer'), ('departure_time', 'interval'),
                ('stop_id', 'integer')],
    'stops': [('stop_lat', 'real'), ('wheelchair_boarding', 'integer'),
            ('stop_code', 'integer'), ('stop_lon', 'real'),
            ('stop_url', 'text'), ('stop_id', 'integer'), ('stop_name', 'text')],
    'trips': [('wheelchair_accessible', 'text'), ('route_id', 'integer'),
              ('trip_id', 'text'), ('trip_headsign', 'text'), ('service_id', 'text')]
    }